# Generated by Django 4.0.4 on 2022-05-15 18:43

from django.db import migrations, models
import django_big_xml.models.xml_export


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMLExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=django_big_xml.models.xml_export.get_token, editable=False, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=django_big_xml.models.xml_export.file_upload_path)),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to=django_big_xml.models.xml_export.file_upload_path)),
                ('is_successful', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
                'get_latest_by': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='xmlexport',
            index=models.Index(fields=['token'], name='xml_export_token_idx'),
        ),
        migrations.AddIndex(
            model_name='xmlexport',
            index=models.Index(fields=['created_at'], name='xml_export_created_at_idx'),
        ),
    ]
